import Head from "next/head";
import React from "react";
import { Header, Footer } from "./index";
import ScrollToTopButton from "../components/ScrollToTopButton"; // ⬅️ import tombolnya

export default function Layout({ children }) {
  return (
    <React.Fragment>
      <Head>
        <title>My Portofolio</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon/favicon.ico"
        />
      </Head>

      <Header />

      <div className="overflow-x-hidden">
        {children}
        <ScrollToTopButton /> 
      </div>

      <Footer />
    </React.Fragment>
  );
}
